[tool.mypy]
python_version = "3.13"
warn_return_any = true
warn_unused_configs = true
disallow_untyped_defs = false  # Temporarily disabled
disallow_incomplete_defs = false  # Temporarily disabled
check_untyped_defs = true
disallow_untyped_decorators = false  # Temporarily disabled
no_implicit_optional = true
warn_redundant_casts = true
warn_unused_ignores = true
warn_no_return = true
warn_unreachable = true
strict_equality = true
show_error_codes = true

[[tool.mypy.overrides]]
module = [
    "requests",
    "kivy.*",
    "flask",
    "aiohttp"
]
ignore_missing_imports = true